baseURL = 'http://panga.network/'
languageCode = 'en-au'
timezone = "Australia/Melbourne"
title = 'My New Hugo Site'

paginate = 50
titlecasestyle = "Go"
readingtime = false

[languages.en]
weight = 10

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
noClasses = false

[markup.tableofcontents]
endlevel = 6
ordered = true
startlevel = 2

[outputs]
home = ["html", "json", "rss"]

[taxonomies]
author = "authors"
category = "categories"
series = "series"
tag = "tags"

[[module.imports]]
path = "github.com/willfaught/paige"
